version: '3.7'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432